name: runner_ipk

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      working-directory: ./
      run: make
    - name: test
      working-directory: ./
      run: ./test_ipk.sh > tests.out
      
      
