name: runner_ipk

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: getdir
      run: ls -l
    - name: make
      run: make
    - name: test
      working-directory: ./
      run: bash ./test_ipk.sh > tests.out
      shell: bash
      
      
